### ISSUE TITLE
Use RAUC project to install/update target

### ISSUE THREAD

**Issue by erickeller** [lueschem/edi#12]
# Issue Type

- Enhancement

# Environment detail

N./A.

# More details

have a look at https://github.com/rauc/rauc

**Comment by lueschem** [comment]
RAUC looks like a very promising and useful addition to the embedded Linux ecosystem!
It makes sense that edi does _not_ cover this aspect by itself but rather provides plugin hooks for easy integration of tools like RAUC.
As far as I understood RAUC, it does currently not care about the initial installation of the target system.
edi could catch up in this area by providing the necessary commands to perform an initial (bare metal) installation of the target system. Furthermore edi could provide some plugins, that facilitate the RAUC integration ("a meta-rauc for Debian").

**Comment by lueschem** [comment]
Closing this issue because we now have a Mender integration that covers the OS image update aspects:
https://www.get-edi.io/Updating-a-Debian-Based-IoT-Fleet/
