### ISSUE TITLE
Remove single point of failure in repository_key

### ISSUE THREAD

**Issue by tacarrie** [lueschem/edi#79]
# Issue Type

- Bug report

# Environment detail

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
+ python3 --version
Python 3.9.2
+ ansible-playbook --version
sh: 3: ansible-playbook: not found
+ lxc --version
sh: 4: lxc: not found
+ grep+ dpkg -l
 \(lxd\|ansible\)
```

- Edi installation method: One of source, pip, ppa
- Ansible installation method: One of source, pip, OS package
- LXD installation method: One of source, pip, OS package

# Desired Behaviour

There shall be no single point of failure with regards to repository_key of base configuration. If a repository is not available for whatever reasons, it shall be possible to use an alternative repository (local or remote).

# Actual Behaviour (Bug report only)

Build was failing last Monday, because the repository was not available:
![image](https://user-images.githubusercontent.com/10333743/209089562-aa4fa1a1-26c6-4f2a-b952-916e1f92d223.png)

![image](https://user-images.githubusercontent.com/10333743/209090371-f816000c-05f5-4ef2-ac76-60d82e6e3a8b.png)

**Comment by lueschem** [comment]
Solved with v2 workflow.
